# Generated by Django 5.2.6 on 2025-09-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curdprac", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("deadline", models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
